name: Bug Report
description: Report a bug building or running Radium
labels: ["bug"]
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Before submitting this bug report, please search existing issues and make sure it's unique.
        If you ignore this text, and create this one, you will be permanently banned from
        interacting with the entire organization.

        If you suspect your bug might apply to all platforms and not just Windows,
        please submit it to the relevant shared "radium" repository instead.
  - type: input
    id: version
    attributes:
      label: Version
      description: Can be copied from radium://settings/help
      placeholder: ex. 133.0.6943.8 r1
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Have you tested that this is not an upstream issue or an issue with your configuration?
      options:
        - label: I have tried reproducing this issue in Chrome and it could not be reproduced there
        - label: I have tried reproducing this issue in ungoogled-chromium and it could not be reproduced there
        - label: I have tried reproducing this issue in Radium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there
          required: true
  - type: input
    id: description
    attributes:
      label: Description
      description: A clear and concise description (in one line) of what the bug is.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: How to Reproduce?
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: A clear and concise description of what actually happened
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here. If applicable, add screenshots to help explain your problem.
